#ifndef ARCH_H_INCLUDED
#define ARCH_H_INCLUDED

// FEAT_SVE             8.2 OPTIONAL
// FEAT_BF16            8.2 OPTIONAL 8.6 MANDATORY
// FEAT_I8MM            8.1 OPTIONAL 8.6 MANDATORY

// FEAT_SVE2            9.0 OPTIONAL
// FEAT_SVE_BitPerm     9.0 OPTIONAL
// FEAT_SVE_PMULL128    9.0 OPTIONAL

#endif // ARCH_H_INCLUDED